# Generated by Django 5.0.4 on 2024-05-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRooms',
            fields=[
                ('room_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('end_date', models.DateField(null=True)),
                ('room_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelrooms')),
            ],
        ),
    ]
