# Generated by Django 5.0.4 on 2024-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhostel',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
