# Generated by Django 5.0.4 on 2024-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_bookhostel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhostel',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
