# Generated by Django 5.0.4 on 2024-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('details', models.TextField()),
            ],
        ),
    ]
